/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package completeretail;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class item extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6171813507319731197L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"item\",\"namespace\":\"completeretail\",\"fields\":[{\"name\":\"itemName\",\"type\":\"string\"},{\"name\":\"itemQuantity\",\"type\":\"int\"},{\"name\":\"itemPrice\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<item> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<item> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<item> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<item> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<item> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this item to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a item from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a item instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static item fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence itemName;
  private int itemQuantity;
  private double itemPrice;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public item() {}

  /**
   * All-args constructor.
   * @param itemName The new value for itemName
   * @param itemQuantity The new value for itemQuantity
   * @param itemPrice The new value for itemPrice
   */
  public item(java.lang.CharSequence itemName, java.lang.Integer itemQuantity, java.lang.Double itemPrice) {
    this.itemName = itemName;
    this.itemQuantity = itemQuantity;
    this.itemPrice = itemPrice;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return itemName;
    case 1: return itemQuantity;
    case 2: return itemPrice;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: itemName = (java.lang.CharSequence)value$; break;
    case 1: itemQuantity = (java.lang.Integer)value$; break;
    case 2: itemPrice = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'itemName' field.
   * @return The value of the 'itemName' field.
   */
  public java.lang.CharSequence getItemName() {
    return itemName;
  }


  /**
   * Sets the value of the 'itemName' field.
   * @param value the value to set.
   */
  public void setItemName(java.lang.CharSequence value) {
    this.itemName = value;
  }

  /**
   * Gets the value of the 'itemQuantity' field.
   * @return The value of the 'itemQuantity' field.
   */
  public int getItemQuantity() {
    return itemQuantity;
  }


  /**
   * Sets the value of the 'itemQuantity' field.
   * @param value the value to set.
   */
  public void setItemQuantity(int value) {
    this.itemQuantity = value;
  }

  /**
   * Gets the value of the 'itemPrice' field.
   * @return The value of the 'itemPrice' field.
   */
  public double getItemPrice() {
    return itemPrice;
  }


  /**
   * Sets the value of the 'itemPrice' field.
   * @param value the value to set.
   */
  public void setItemPrice(double value) {
    this.itemPrice = value;
  }

  /**
   * Creates a new item RecordBuilder.
   * @return A new item RecordBuilder
   */
  public static completeretail.item.Builder newBuilder() {
    return new completeretail.item.Builder();
  }

  /**
   * Creates a new item RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new item RecordBuilder
   */
  public static completeretail.item.Builder newBuilder(completeretail.item.Builder other) {
    if (other == null) {
      return new completeretail.item.Builder();
    } else {
      return new completeretail.item.Builder(other);
    }
  }

  /**
   * Creates a new item RecordBuilder by copying an existing item instance.
   * @param other The existing instance to copy.
   * @return A new item RecordBuilder
   */
  public static completeretail.item.Builder newBuilder(completeretail.item other) {
    if (other == null) {
      return new completeretail.item.Builder();
    } else {
      return new completeretail.item.Builder(other);
    }
  }

  /**
   * RecordBuilder for item instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<item>
    implements org.apache.avro.data.RecordBuilder<item> {

    private java.lang.CharSequence itemName;
    private int itemQuantity;
    private double itemPrice;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(completeretail.item.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.itemName)) {
        this.itemName = data().deepCopy(fields()[0].schema(), other.itemName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.itemQuantity)) {
        this.itemQuantity = data().deepCopy(fields()[1].schema(), other.itemQuantity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.itemPrice)) {
        this.itemPrice = data().deepCopy(fields()[2].schema(), other.itemPrice);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing item instance
     * @param other The existing instance to copy.
     */
    private Builder(completeretail.item other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.itemName)) {
        this.itemName = data().deepCopy(fields()[0].schema(), other.itemName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.itemQuantity)) {
        this.itemQuantity = data().deepCopy(fields()[1].schema(), other.itemQuantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.itemPrice)) {
        this.itemPrice = data().deepCopy(fields()[2].schema(), other.itemPrice);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'itemName' field.
      * @return The value.
      */
    public java.lang.CharSequence getItemName() {
      return itemName;
    }


    /**
      * Sets the value of the 'itemName' field.
      * @param value The value of 'itemName'.
      * @return This builder.
      */
    public completeretail.item.Builder setItemName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.itemName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'itemName' field has been set.
      * @return True if the 'itemName' field has been set, false otherwise.
      */
    public boolean hasItemName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'itemName' field.
      * @return This builder.
      */
    public completeretail.item.Builder clearItemName() {
      itemName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'itemQuantity' field.
      * @return The value.
      */
    public int getItemQuantity() {
      return itemQuantity;
    }


    /**
      * Sets the value of the 'itemQuantity' field.
      * @param value The value of 'itemQuantity'.
      * @return This builder.
      */
    public completeretail.item.Builder setItemQuantity(int value) {
      validate(fields()[1], value);
      this.itemQuantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'itemQuantity' field has been set.
      * @return True if the 'itemQuantity' field has been set, false otherwise.
      */
    public boolean hasItemQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'itemQuantity' field.
      * @return This builder.
      */
    public completeretail.item.Builder clearItemQuantity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'itemPrice' field.
      * @return The value.
      */
    public double getItemPrice() {
      return itemPrice;
    }


    /**
      * Sets the value of the 'itemPrice' field.
      * @param value The value of 'itemPrice'.
      * @return This builder.
      */
    public completeretail.item.Builder setItemPrice(double value) {
      validate(fields()[2], value);
      this.itemPrice = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'itemPrice' field has been set.
      * @return True if the 'itemPrice' field has been set, false otherwise.
      */
    public boolean hasItemPrice() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'itemPrice' field.
      * @return This builder.
      */
    public completeretail.item.Builder clearItemPrice() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public item build() {
      try {
        item record = new item();
        record.itemName = fieldSetFlags()[0] ? this.itemName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.itemQuantity = fieldSetFlags()[1] ? this.itemQuantity : (java.lang.Integer) defaultValue(fields()[1]);
        record.itemPrice = fieldSetFlags()[2] ? this.itemPrice : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<item>
    WRITER$ = (org.apache.avro.io.DatumWriter<item>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<item>
    READER$ = (org.apache.avro.io.DatumReader<item>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.itemName);

    out.writeInt(this.itemQuantity);

    out.writeDouble(this.itemPrice);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.itemName = in.readString(this.itemName instanceof Utf8 ? (Utf8)this.itemName : null);

      this.itemQuantity = in.readInt();

      this.itemPrice = in.readDouble();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.itemName = in.readString(this.itemName instanceof Utf8 ? (Utf8)this.itemName : null);
          break;

        case 1:
          this.itemQuantity = in.readInt();
          break;

        case 2:
          this.itemPrice = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










