spring:
  cloud:
    function:
      definition: publishOrder
    stream:
      bindings:
        publish-out-0:
          destination: test/retail/stream/order/new
          binder: local-solace
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcps://mr-connection-ue89hsrd3g0.messaging.solace.cloud:55443
                msgVpn: testssh
                clientUsername: solace-cloud-client
                clientPassword: 4kgqg5g4b2jlooakeukpq8qqr6
      # bindings:
      #   publish-out-0:
      #     destination: new.orders
      #     binder: rabbit1
      # binders:
      #   rabbit1:
      #     type: rabbit
      #     environment:
      #       spring:
      #         rabbitmq:
      #           host: localhost
      #           port: 5673
      #           username: guest
      #           password: guest


server:
  port: 8093